# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9f2a952ea68fc9fbe9fcc64d820a69dc3f26dc308ac78ee223d5cfedaaa3091f6fd0191db94a04f05bb0e99acc8946739fb25ed71478bc8ce7b0b6f62c77b61

test:
  secret_key_base: df54b1c93563bc78ae1a9c7d1a9557071b89dcdd928cfc4a388b1f6f8be1aca6df6c36c0a5d750b5187694fcd18aa3a228421c4bfa42df13432d91b055c885fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
